import org.objectweb.asm.*;
import java.io.*;
import java.util.zip.*;

/**
 * Patches kotlin-compiler.jar: adds getExtensions(ExtensionPointName) to Extensions.
 *
 * Problem: CodeStyleSettings (from openapi-formatter.jar) calls
 * Extensions.getExtensions(ExtensionPointName) which exists in intellij-core's full Extensions
 * but not in kotlin-compiler's minimal Extensions stub (which only has setRootArea/getRootArea).
 *
 * Fix: add the method that delegates to getRootArea().getExtensionPoint(name).getExtensions().
 * The generated bytecode is equivalent to:
 *   public static <T> T[] getExtensions(ExtensionPointName<T> name) {
 *       return getRootArea().getExtensionPoint(name).getExtensions();
 *   }
 */
public class PatchExtensionsAddGetExtensions {
    static final String EXTENSIONS   = "com/intellij/openapi/extensions/Extensions";
    static final String EPN          = "com/intellij/openapi/extensions/ExtensionPointName";
    static final String EP           = "com/intellij/openapi/extensions/ExtensionPoint";
    static final String AREA         = "com/intellij/openapi/extensions/ExtensionsArea";

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("Usage: PatchExtensionsAddGetExtensions <input.jar> <output.jar>");
            System.exit(1);
        }

        try (ZipInputStream zin = new ZipInputStream(new FileInputStream(args[0]));
             ZipOutputStream zout = new ZipOutputStream(new FileOutputStream(args[1]))) {

            ZipEntry entry;
            while ((entry = zin.getNextEntry()) != null) {
                String name = entry.getName();
                byte[] bytes = zin.readAllBytes();

                if (name.equals(EXTENSIONS + ".class")) {
                    System.out.println("Patching Extensions (adding getExtensions)...");
                    bytes = patchClass(bytes);
                }

                ZipEntry outEntry = new ZipEntry(name);
                zout.putNextEntry(outEntry);
                zout.write(bytes);
                zout.closeEntry();
            }
        }
        System.out.println("Done.");
    }

    static byte[] patchClass(byte[] original) {
        ClassReader cr = new ClassReader(original);
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_MAXS);

        cr.accept(new ClassVisitor(Opcodes.ASM9, cw) {
            @Override
            public void visitEnd() {
                // Add: public static Object[] getExtensions(ExtensionPointName name) {
                //          return getRootArea().getExtensionPoint(name).getExtensions();
                //      }
                MethodVisitor mv = cv.visitMethod(
                    Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                    "getExtensions",
                    "(L" + EPN + ";)[Ljava/lang/Object;",
                    "<T:Ljava/lang/Object;>(L" + EPN + "<TT;>;)[TT;",
                    null
                );
                mv.visitCode();

                // getRootArea()
                mv.visitMethodInsn(Opcodes.INVOKESTATIC, EXTENSIONS, "getRootArea",
                    "()L" + AREA + ";", false);

                // .getExtensionPoint(name)
                mv.visitVarInsn(Opcodes.ALOAD, 0);
                mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, AREA, "getExtensionPoint",
                    "(L" + EPN + ";)L" + EP + ";", true);

                // .getExtensions()
                mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, EP, "getExtensions",
                    "()[Ljava/lang/Object;", true);

                mv.visitInsn(Opcodes.ARETURN);
                mv.visitMaxs(2, 1);
                mv.visitEnd();

                System.out.println("  Added getExtensions(ExtensionPointName)");
                super.visitEnd();
            }
        }, 0);

        return cw.toByteArray();
    }
}
